apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-sql
  namespace: postgresql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS students (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100),
      age INT,
      phone BIGINT
    );
