apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: python-app
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
