replicaCount: 2

image:
  repository: 905418146175.dkr.ecr.eu-central-1.amazonaws.com/python-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

env:
  DB_NAME: mydb
  DB_USER: grozdimir
  DB_HOST: postgresql.postgresql.svc.cluster.local
  DB_PORT: "5432"
  DB_PASSWORD_SECRET:
    name: python-app-to-postgresql
    key: password

